### ISSUE TITLE
Change inset amount in the i3 config file

### ISSUE THREAD

**Issue by asonix** [stlukey/i3#2]
There was a very similar patch for i3 by DSMan195276 (found here: https://github.com/DSMan195276/i3/tree/dsm-changes) which is now outdated, but it was able to control the inset amount through the configuration file.

Would it be possible to replicate that functionality with your patch?

**Comment by jbegaint** [comment]
~~yes, only the command line seems to differ: "gap_size X " instead of "new_window inset X".~~

edit: see pull request #1

**Comment by asonix** [comment]
What I meant is in the .i3/config file, there was a parameter to change the gap size that didn't require recompiling the entire wm. I wrote a quick python script and mapped keys to it to change the inset on the fly. I would rather not have to recompile i3 each time I want to change the inset.

**Comment by jbegaint** [comment]
ok my bad, (monday morning...)

For now, there's no parameter in this patch to change the inset on the fly, but that's exactly what my pull request (#1) implements.

If you can test it on your side, it may helps getting it merged...

**Comment by stlukey** [comment]
Pull request #1 implements this perfectly (thanks @jeanbroid), it has now been merged.
