### ISSUE TITLE
Merge i3 v4.8

### ISSUE THREAD

**Issue by Airblader** [stlukey/i3#3]
There is i3 v4.8 by now which is not yet merged into the gaps branch. I just did the merge (see my fork). It was fairly straight-forward and upon first testing seems to work fine.

I'd issue a pull request, but I'm not sure how this project would want the pull request since I'd probably have to use another remote (the actual i3 repository).

**Comment by stlukey** [comment]
I have just merged the gaps branch with the latest version of i3 (6b1f3f7)
