### ISSUE TITLE
Gaps between windows are 2x width of gaps between windows and screen edge

### ISSUE THREAD

**Issue by aarobc** [stlukey/i3#5]
I've attached a screenshot below, The proper behavior would be for the gaps to maintain a consistent width from other windows and from the screen edge.

I've increased the gap size to 20 in the screenshot below to emphasize the issue:

![selection_015](https://cloud.githubusercontent.com/assets/247606/5795851/fd6743f8-9f56-11e4-9f77-b304f537afa6.png)

**Comment by stlukey** [comment]
I have noticed this too but have been unable to find the time to fix it yet.

**Comment by Airblader** [comment]
Not to draw attention away from this fork, but my fork which was originally based on this fork contains a fix for this issue.
